[package]
name = "massa-sc-runtime"
version = "0.6.9"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1"
serde = "1.0"
serde_json = "1.0"
wasmer = { version = "2.3.0" }
as-ffi-bindings = "0.2.5"
wasmer-compiler-singlepass = { version = "2.3.0" }
wasmer-engine-universal = { version = "2.3.0" }
wasmer-middlewares = { version = "2.3.0" }
cornetto = "0.1"
base64 = "0.13"
serial_test = "0.8"
loupe = "0.1"
parking_lot = "0.12"
rand = "0.8"
