[package]
name = "assembly_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
lazy_static = "1"
serde = "1.0"
serde_json = "1.0"
wasmer = "2.0.0"
wasmer-as = { git = "https://github.com/adrien-zinger/wasmer-as", tag = "v0.1.0" }
wasmer-compiler-cranelift = "2"
wasmer-engine-universal = "2"
wasmer-middlewares = "2"
cornetto = "0.1.0"
